### Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [1]:
import numpy as np

np.vander(np.arange(1,10), 3, True)

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  4, 16],
       [ 1,  5, 25],
       [ 1,  6, 36],
       [ 1,  7, 49],
       [ 1,  8, 64],
       [ 1,  9, 81]])

In [14]:
# Similar implementation without vander function
x = np.arange(1,9)
np.sort(np.column_stack([x**(2-i) for i in range(3)]), axis = 1)

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  4, 16],
       [ 1,  5, 25],
       [ 1,  6, 36],
       [ 1,  7, 49],
       [ 1,  8, 64]], dtype=int32)

### Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:

The moving average sequence has n-k+1 elements as shown below. <br>
The moving averages with k=4 of a ten-value sequence (n=10) is shown below <br>
i 1 2 3 4 5 6 7 8 9 10 <br>
===== == == == == == == == == == == <br>
Input 10 20 30 40 50 60 70 80 90 100 <br>
y1 25 = (10+20+30+40)/4 <br>
y2 35 = (20+30+40+50)/4<br>
y3 45 = (30+40+50+60)/4<br>
y4 55 = (40+50+60+70)/4<br>
y5 65 = (50+60+70+80)/4<br>
y6 75 = (60+70+80+90)/4<br>
y7 85 = (70+80+90+100)/4<br>
Thus, the moving average sequence has n-k+1=10-4+1=7 values.<br>

Write a function to find moving average in an array over a window:<br>
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [10]:
data = np.asarray([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])

In [11]:
def moving_average(data_set, periods=4):
    weights = np.ones(periods) / periods
    return np.convolve(data_set, weights, mode='valid')   # Returns a linear convolution of a two dimensional 1d array

In [12]:
moving_average(data, 3)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])

In [15]:
# Normal Method
def moving_average(data_set, periods):
    mov_avg_sea = []
    for i in range(0, (len(data_set) - periods + 1)):
        # slice the data and get the cumsum
        mov_avg_sea.append(data_set[i: i + periods].cumsum()[2]/periods)
    return np.asarray(mov_avg_sea)

In [16]:
moving_average(data, 3)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])